### ISSUE TITLE
Nythz

### ISSUE THREAD

**Issue by rolkoztm** [MrBoombastic/nosaczapi-unofficial#3]
Witam
proszę dodać do sali sław ( Nythz )
https://nythzbot.tk

https://images-ext-2.discordapp.net/external/zA9byNnqj6fl3wZO6OubR41CYBFfXxXT9JVwfuc31MQ/%3Fsize%3D1024/https/cdn.discordapp.com/avatars/723210798146781230/ac8ca2680f24d2ef36be861297653d59.webp?width=475&height=475

Pozdrawiam serdecznie RolkozTM

**Comment by MrBoombastic** [comment]
Można prosić o normalny link do obrazka?

**Comment by rolkoztm** [comment]
Prosze : https://i.imgur.com/q82AXLs.jpg

**Comment by MrBoombastic** [comment]
Dodano.

**Comment by MrBoombastic** [comment]
Żartowałem.

**Comment by rolkoztm** [comment]
Ty pranksterze, Marcin Dubiel v2

**Comment by Korrumz2PL** [comment]
haha 69

**Comment by jelni** [comment]
> haha 69

to zabawne
