### ISSUE TITLE
KURRŁA SOMSIADY MI POMYS KRADNO

### ISSUE THREAD

**Issue by Szprinktrap** [MrBoombastic/nosaczapi-unofficial#5]
Nah, jk XDDD
Dobra robota z tym backupem

P.S  Mój nick na discordzie sie zmienił, teraz jest to Szprink#3425

**Comment by MrBoombastic** [comment]
Dzienki za miłe słówka XD. Nick zaktualizuję, nie ma problemu.

**Comment by rolkoztm** [comment]
hot
