### ISSUE TITLE
FiveBit

### ISSUE THREAD

**Issue by tom-masz** [MrBoombastic/nosaczapi-unofficial#7]
dżem dobry dżem dobry chciałbym tylko powiedzieć że ktoś [fivebita](https://fivebit.tk) ukradł z hali sław kiedyś a no bot korzysta to kurła reklame trzeba kreńcić
![avatar](https://user-images.githubusercontent.com/61909942/116793010-7a791680-aac4-11eb-9cbf-7b937a11c301.png)

**Comment by tom-masz** [comment]
o kurwa troche duży ten avek XDDD

**Comment by MrBoombastic** [comment]
Done
